//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Documentor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Documentor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub Repository Documentor.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        internal static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (C)2020 Nick Beaugeard.
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to created on.
        /// </summary>
        internal static string CreatedOn {
            get {
                return ResourceManager.GetString("CreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Open Issues.
        /// </summary>
        internal static string CurrentOpenIssues {
            get {
                return ResourceManager.GetString("CurrentOpenIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Created.
        /// </summary>
        internal static string DateCreated {
            get {
                return ResourceManager.GetString("DateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Branch.
        /// </summary>
        internal static string DefaultBranch {
            get {
                return ResourceManager.GetString("DefaultBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headers.
        /// </summary>
        internal static string Headers {
            get {
                return ResourceManager.GetString("Headers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Id.
        /// </summary>
        internal static string IssueId {
            get {
                return ResourceManager.GetString("IssueId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issues.
        /// </summary>
        internal static string Issues {
            get {
                return ResourceManager.GetString("Issues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issues modified in last 30 days.
        /// </summary>
        internal static string IssuesModified30 {
            get {
                return ResourceManager.GetString("IssuesModified30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Update.
        /// </summary>
        internal static string Last_Update {
            get {
                return ResourceManager.GetString("Last Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Code Update.
        /// </summary>
        internal static string LastCodeUpdate {
            get {
                return ResourceManager.GetString("LastCodeUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        internal static string Modified {
            get {
                return ResourceManager.GetString("Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        internal static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Issues.
        /// </summary>
        internal static string Open_Issues {
            get {
                return ResourceManager.GetString("Open Issues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall Information.
        /// </summary>
        internal static string OverallInfo {
            get {
                return ResourceManager.GetString("OverallInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait, constructing report....
        /// </summary>
        internal static string PlsWait {
            get {
                return ResourceManager.GetString("PlsWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Number.
        /// </summary>
        internal static string Project_Number {
            get {
                return ResourceManager.GetString("Project Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Status.
        /// </summary>
        internal static string Project_Status {
            get {
                return ResourceManager.GetString("Project Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        internal static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Status Report.
        /// </summary>
        internal static string ReportTitle {
            get {
                return ResourceManager.GetString("ReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specification.
        /// </summary>
        internal static string Specification {
            get {
                return ResourceManager.GetString("Specification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specification for.
        /// </summary>
        internal static string SpecificationFor {
            get {
                return ResourceManager.GetString("SpecificationFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Report for.
        /// </summary>
        internal static string StatusReportFor {
            get {
                return ResourceManager.GetString("StatusReportFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        internal static string Step {
            get {
                return ResourceManager.GetString("Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribers.
        /// </summary>
        internal static string Subscribers {
            get {
                return ResourceManager.GetString("Subscribers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no cards in this column.
        /// </summary>
        internal static string ThereAreNoIssuesinThisStatus {
            get {
                return ResourceManager.GetString("ThereAreNoIssuesinThisStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working on card.
        /// </summary>
        internal static string Working_on_card {
            get {
                return ResourceManager.GetString("Working on card", resourceCulture);
            }
        }
    }
}
